### ISSUE TITLE
Fetch command outputs nothing and never exits

### ISSUE THREAD

**Issue by OiYouYeahYou** [cooklang/CookCLI#17]
Running on Linux I've tried running `cook fetch` with no other arguments and left it for several hours. Also, if you run `cook fetch .` the application has a fatal error, causing a an `illegal hardware instruction`.

Version: `v0.0.9 – in food we trust`

**Comment by VageGast** [comment]
I got the following, probably related, error when running the fetch command:

```
❯ cook fetch "Baked Potato Soup.cook"
Foundation/NSSwiftRuntime.swift:401: Fatal error: You must link or load module FoundationNetworking to load non-file: URL content using String(contentsOf:…), Data(contentsOf:…), etc.
[1]    31882 illegal hardware instruction (core dumped)  cook fetch "Baked Potato Soup.cook"


❯ cook version
v0.0.9 – in food we trust
```

OS: Linux Mint 19.3
