### ISSUE TITLE
User customisation of default headers generated from cook-recipe-read

### ISSUE THREAD

**Issue by edibotopic** [cooklang/CookCLI#19]
The default output generated from:

```bash
cook recipe read <recipe-file>
```

Generates a structure with four headers: **Metadata**, **Ingredients**, **Cookware**, **Steps**.
_Is it possible to change these headings for specific cases where alternate headings are preferred?_

For example, files being shared within a small food manufacturer could be given the corresponding headers: **Product**, **Materials**, **Equipment**, **Operations**.

**Comment by dubadub** [comment]
@edibotopic first what comes to my mind is to modify headers in [the source code](https://github.com/cooklang/CookCLI/blob/d1d4b4a3af56230ca46c510823b498193ff35078/Sources/CookCLI/Printable/CookRecipe%2BPrintable.swift#L63) and build your own version. Depending on how it's going to be used maybe it's suitable for you to output into JSON and using `jq` or something to create desired output. If you can give more details I might be able to help you.

**Comment by edibotopic** [comment]
Thanks @dubadub : I can work with those suggestions for now.

I think this might be an interesting tool for people working in a more industrial capacity - in a sense, many scientists, technologists and engineers work with "recipes" while not necessarily using culinary terminology. This might be out-of-scope though.

I will consider your suggestion and maybe fork the repo. A config file where some of these defaults could be changed would be best. I am not a professional programmer and am unfamiliar with Swift but can probably muddle through.

This is the first issue I've posted on Github😊 - I think it can be closed now though.

**Comment by Artees** [comment]
@edibotopic Why not just pipe it into sed? If you're on Linux or Mac:
`cook recipe read <recipe-file> | sed "s/Ingredients/Materials/"`

**Comment by edibotopic** [comment]
Yup @Artees, this works — thank you for the suggestion — I can then make multiple substitutions with `cook recipe read <recipe-file> | sed "s/Ingredients/Materials/; s/Cookware/Equipment/"` and so on. Perhaps make a bash/zsh alias for when `cook recipe read` is invoked.

Originally, I was considering a case where I was recommending the tool to multiple users, some with limited Linux/Unix or CLI experience, and who just wanted it to work with more familiar terminology out-of-the-box. I thought it might be preferable if they could modify a config file as needed but your suggestion is a workable solution for now.

**Comment by dubadub** [comment]
@edibotopic I'm closing this issue, feel free to open one again if you have problems with building the app or need any other help.
