### ISSUE TITLE
HomeBrew integration

### ISSUE THREAD

**Issue by umgefahren** [cooklang/CookCLI#3]
It would be amazing, if the tool would be available over HomeBrew.

Ressources:
- [Adding Software to Home-brew](https://docs.brew.sh/Adding-Software-to-Homebrew)

**Comment by dubadub** [comment]
@theunraveler thanks for your help with setting it up. I added workflow in https://github.com/cooklang/homebrew-tap and now it pre-builds universal binary for both architectures and adds them to releases. I still prefer to use tap as it's easier to maintain.
