### ISSUE TITLE
Metadata in recipe file when using the output-format

### ISSUE THREAD

**Issue by markstar** [cooklang/CookCLI#31]
When using the `cook recipe read` method with the `--output-format` option, it would be great if you could output the metadata for the recipe, along with the cookware, ingredients and method.

p.s. love the library!

**Comment by dubadub** [comment]
@markstar great idea! We will add that into next release.

**Comment by dubadub** [comment]
Added into https://github.com/cooklang/CookCLI/releases/tag/v0.1.3 release.
