### ISSUE TITLE
[suggestion] generate formatted .md files using cooklang

### ISSUE THREAD

**Issue by flynneva** [cooklang/cookcli#32]
First off - love this idea and the effort put into it so far!

This is more of a question / suggestion than an issue, but would it be possible to generate `.md` files using the cookcli? Essentially converting the `.cook` file to an `.md` so I could put it on github or gitlab and have it auto-formatted?

**Comment by dubadub** [comment]
@flynneva I'm not sure I understood what you mean. Do you suggest to create an `.md` recipe file in classical recipe view with ingredients first and method using Markdown syntax?

**Comment by dubadub** [comment]
By `auto-formatting` do you mean file rendering into HTML?

**Comment by flynneva** [comment]
> By auto-formatting do you mean file rendering into HTML?

@dubadub no I mean what you say in the previous comment: some template `.md` classical recipe view with ingredients first and method after, maybe with one picture as well at the top or something.

**Comment by skoenig** [comment]
I think this could be implemented as another `output-format` for the `recipe read` subcommand pretty easy. @dubadub What do you think?

**Comment by dubadub** [comment]
@skoenig, yes, exactly! I have other priorities right now, but it should be easy enough to do if someone wants to give it a try. I created a page about how to [setup development environment](https://github.com/cooklang/CookCLI/blob/main/CONTRIBUTING.md) and can help with any questions.

**Comment by dubadub** [comment]
This was added in a Rust version. One can run `cook recipe --format md ./Borsch.cook` to get Markdown version.

```
---
servings:
- 6
---

# 

## Ingredients
- *3 medium* beetroots
- *3 medium* potatoes
- *3 items* carrots
- *2 tbsp* olive oil
- *8 cups* chicken broth
- *2 cups* water
- *2 tbsp* olive oil
- *1 medium* onion
- *2 items* celery
- *1 small* bell pepper
- *3 tbsp* tomato paste
- *1 can* cannellini beans
- *2 items* bay leaves
- *2 tbsp* white vinegar
- *1 tsp* salt
- *4 tsp* black pepper
- *1 glove* garlic
- *3 tbsp* dill

## Cookware
- large soup pot

## Steps
1. Peel, grate and/or slice beetroots, potatoes and carrots. Keep sliced
potatoes in cold water to prevent browning until ready to use then drain.

2. Heat a large soup pot of 5L or larger over medium/high heat and add olive
oil. Add grated beets and sauté 10 minutes, stirring occasionally until beets
are softened.

3. Add chicken broth and water. Add sliced potatoes and sliced carrots then cook
for 10-15 minutes or until easily pierced with a fork.

4. While potatoes are cooking, place a large skillet over medium/high heat and
add olive oil. Add finally chopped onion, celery and bell pepper. Saute stirring
occasionally until softened and lightly golden for 7-8 minutes. Add tomato paste
and stir fry 30 seconds then transfer to the soup pot to continue cooking with
the potatoes.

5. When potatoes and carrots reach desired softness, add cannellini beans with
their juice, bay leaves, white vinegar, salt, black pepper, pressed garlic, and
chopped dill. Simmer for an additional 2-3 minutes and add more salt and vinegar
to taste.
```
