### ISSUE TITLE
Server segmentation fault when navigating to shopping list

### ISSUE THREAD

**Issue by nilpunning** [cooklang/CookCLI#33]
Reproduction steps:
```zsh
brew tap cooklang/tap
brew install cooklang/tap/cook
cook version
# v0.1.2 – in food we trust
mkdir recipes
cook seed ./recipes
cook server ./recipes
# Started server on http://127.0.0.1:9080, serving cook files from ./recipes.
# Navigate to http://localhost:9080/
# Navigate to http://localhost:9080/shopping-list
# zsh: segmentation fault  cook server ./recipes
```

**Comment by nilpunning** [comment]
When building from within Xcode this bug does not surface.   But when attaching xCode debugger to running command, it appears to crash in the Embassy code.  It looks like it could be related to this issue: https://github.com/envoy/Embassy/issues/96.

**Comment by dubadub** [comment]
@nilpunning thanks for reporting and debugging. Turns out there's a bugfix for the issue to be merged.
