### ISSUE TITLE
Improve build documentation

### ISSUE THREAD

**Issue by SebRut** [cooklang/CookCLI#4]
Hi,

I'm trying to prepare an arch linux package for this but the build documentation is kinda lacking. Right now I got it boiled down to this:

1. checkout code
2. run `make prepare` (this fails on linux because of different sed implementations and I guess you need node and something called `rollup.js` too?)
3. run `swift build --configuration release -Xswiftc -static-stdlib`
4. take binary from `.build/x86_64-unknown-linux-gnu/release/cook`

**Comment by jsbmg** [comment]
Regarding sed and Linux, what platform would this work to build on?

**Comment by Scoder12** [comment]
Considering swift is an apple centric language I would make an educated guess that it works on mac.

**Comment by SebRut** [comment]
IIRC the problem is that macOS ships with BSD sed while most linuxes ship with GNU sed which are not completely compatible. It seems like using GNU sed on macOS would be as simple as installing `gsed` with homebrew und using that instead of sed.

**Comment by dubadub** [comment]
@SebRut thanks for bringing this up. I'll add the document shortly. Your flow is completely right, except that you don't need to do step 2: it's only required during development to update inlined assets in code.

**Comment by dubadub** [comment]
I added build instructions https://github.com/cooklang/CookCLI#building-from-source for users. Will close this issue after adding build instructions for developers.

**Comment by dubadub** [comment]
Added [contribution guidelines](https://github.com/cooklang/CookCLI/blob/main/CONTRIBUTING.md).
