### ISSUE TITLE
[Question] Does the arm64 binary work on Android using Termux?

### ISSUE THREAD

**Issue by shayaknyc** [cooklang/CookCLI#53]
Hey - in case I haven't mentioned it, I'm absolutely IN LOVE with this project! I've already started converting many of my own recipes into this format, and it's been so immeasurably helpful. 

I often use Termux on my android device, and tried to run the arm64 binary on it, but when I do, I get the error:
```
29950 invalid system call cook
```

Am I doing something wrong?

**Comment by dubadub** [comment]
Thank you @shayaknyc for your kind words.

> I often use Termux on my android device, and tried to run the arm64 binary on it, but when I do, I get the error:

Never used Termux and I'd not sure how it works. I don't have any Android device to check, but their website mentions that it supports `strace` and `gdb`. If you can get more details what command do you run and post strace output it will help to make some guesses. 

Thanks.

**Comment by dubadub** [comment]
Nice! It turned out easier than I expected :-)
