### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by dubadub** [cooklang/cookcli#56]
Right now we only build binaries for macOS and Linux. Swift is officially supported on Windows now, so we can explore options to build CLI to work natively on Windows.

- [ ] Migrate hardcoded slashes in paths to cross platform helpers.
- [ ] Search for https://github.com/weichsel/ZIPFoundation.git alternative supported on Windows or submit a patch for upstream repo.
- [ ] Submit a patch to upstream https://github.com/envoy/Embassy.git to support Windows.

**Comment by ThatTSGuy** [comment]
If you'd rather someone else do it, I could build it with TypeScript and use [pkg](https://github.com/vercel/pkg) to turn it into an executable. Shouldn't be too hard as I've already build the parser and Svelte just needs a HTTP server to serve it.

**Comment by victorwestmann** [comment]
It would be indeed lovely to be able to also run this super cool programming language on Windows platform. 😃

**Comment by ThatTSGuy** [comment]
> It would be indeed lovely to be able to also run this super cool programming language on Windows platform. 😃 

I'm currently working on an implementation. School and work are my current focus though and it may be at least a few months till I'm finished.

**Comment by victorwestmann** [comment]
No problem at all! Just to know that there is someone looking into it and that we might have this sometime next year is already thrilling! Thank you for the heads up. I have 2 huge notebooks to transcribe and having found cooklang is very inspiring! Will you also offer a place to publish the recipes like MuseScore does to scores? If not, that's super fine as well!

**Comment by ThatTSGuy** [comment]
Maybe sometime in the future, but that's probably something the me and the organization will have to work out due to hosting requirements and other stuff.

**Comment by dubadub** [comment]
I migrated CLI to rust and now we have Windows support. You can download binary from [the releases](https://github.com/cooklang/cookcli/releases).
