### ISSUE TITLE
Generate static website from recipes

### ISSUE THREAD

**Issue by shicks** [cooklang/cookcli#58]
The `cook server` is great, but it's not practical to use without a computer to serve it on.  It would be really nice to be able to generate a static website from a recipe book that could be deployed to (say) GitHub Pages, and then used the same way as the existing server (keeping all the shopping list state client-side, if it isn't already).

**Comment by dubadub** [comment]
Interesting idea. Yes, client side is written in Svelte and can be reused. I think it's relatively easy to do. It goes down to creating a build process which generates a few API JSONs in `/api` directory.

Somewhat related links: https://github.com/gohugoio/hugo/issues/9602 and https://github.com/cooklang/CookCLI/issues/32.

**Comment by bubonicfred** [comment]
There is an eleventy plugin btw https://github.com/matt-auckland/eleventy-plugin-cooklang

**Comment by dubadub** [comment]
I don't think we going to implement that any time soon. Closing it
