### ISSUE TITLE
Workflow to work with Javascript

### ISSUE THREAD

**Issue by theslyprofessor** [cooklang/CookCLI#6]
Hello,
I was wondering if there was a way to make this work with web browsers, so that a Javascript function can process the parsed results of cooklang.

Thanks,
Nakul

**Comment by dubadub** [comment]
Not really clear what is the question, I'm closing it. Please, feel free to open again.

**Comment by ThatTSGuy** [comment]
@theslyprofessor you can now use [cooklang-ts](https://github.com/cooklang/cooklang-ts) for parsing and manipulating  Cooklang recipes in the browser or Node.js.
