### ISSUE TITLE
Feature request: Wrap text for Steps in `recipe read`'s text output

### ISSUE THREAD

**Issue by higgins** [cooklang/CookCLI#62]
Hello! Love this tool so far.

It looks like a recipe's steps are required to be on a single line. When reading the recipe via the cli-tool (eg: `cook recipe read Baked\ Potato\ Soup.cook`) each step is rendered on a line which takes the full length of the terminal window (see screenshot below).

**Feature request**: can this output be wrapped to 80 characters or made configurable what the line width should be?

IMO, this would make for more readable recipe cards.

<img width="1436" alt="Screen Shot 2022-05-25 at 11 01 16 AM" src="https://user-images.githubusercontent.com/876147/170336523-27bb8bf2-bbe5-49f8-ae17-2df222adee9d.png">

**Comment by dubadub** [comment]
@higgins great idea, it makes a lot of sense. I can check during the weekend, it shouldn't the hard.

**Comment by higgins** [comment]
@dubadub excellent, thanks for taking a look!

**Comment by dubadub** [comment]
Sorry @higgins , I hadn't got a chance yet.

**Comment by dubadub** [comment]
He @higgins, this has been released in https://github.com/cooklang/CookCLI/releases/tag/v0.1.5. Thanks for idea!

**Comment by higgins** [comment]
heck yeah! thanks @dubadub! 🏆
