### ISSUE TITLE
Produce consistent output

### ISSUE THREAD

**Issue by jamie** [cooklang/cookcli#67]
When running `cook recipe file.cook`, cookware and ingredients are output in a random order. It would be nicer for readers if they were presented in a consistent fashion.

For cookware, I'd argue "in the order listed in the recipe" is the most consistent.

For ingredients, there's a few options (I favour the latter):

- In order of use in recipe
- By amount, largest first
- Alphabetically, or alphabetically grouped by shopping-list category (as long as we have categories available, grouping veggies, spices, etc. in the recipe output is helpful)

Regardless of order chosen, it should be consistent for all output formats.

**Comment by dubadub** [comment]
It is now consistent and displays ingredients in the order listed in the recipe.
