### ISSUE TITLE
Add support for ingredient unit: % 

### ISSUE THREAD

**Issue by D4ntin** [cooklang/cookcli#70]
I just tried to write down this recipe from [Glen and Friend's Cooking](https://youtu.be/VjuetadNtBo) in cooklang when I discovered that there is no way of escaping the % character for ingredient units.

The recipe in the description of the video calls for `100% chicken bones`.

I tried `@chicken bones{100%%}` and got `100 chicken bones` :laughing: 
Tested it in [the playground](https://biowaffeln.github.io/cooklang-parser/).

**Comment by dubadub** [comment]
thanks for filing an issue, good catch!

**Comment by dubadub** [comment]
This was fixed in a new Rust parser.
