### ISSUE TITLE
Provide ARM binaries for MacOS/Linux for future releases

### ISSUE THREAD

**Issue by SamuSoft** [cooklang/cookcli#76]
When running on M1 Macs the only way to use the CLI is to do a local compilation, requiring the full installation of XCode. It would be prefereable to create binaries for ARM-arch as well as the AMD ones in the future

**Comment by dubadub** [comment]
@SamuSoft I migrated CLI to rust and now we have ARM version as well. At the moment it's not notarised yet, I will add notarisation soon. You can download binary from [the releases](https://github.com/cooklang/cookcli/releases).
