### ISSUE TITLE
Compiling for aarch64 from v0.4.0+ breaks with missing/broken OpenSSL dependancy

### ISSUE THREAD

**Issue by shayaknyc** [cooklang/cookcli#84]
Noticed the new release, but not seeing the linux executable in the releases....possible to compile locally for arm64 arch following the docs in the readme?

**Comment by shayaknyc** [comment]
Just a quick update....with a little googling and help from chatgpt, I did the following:
`rustup target add aarch64-unknown-linux-gnu`
then:
`sudo pacman -S aarch64-linux-gnu-gcc`
then cloned the repo, changed into the `ui` directory and did the `npm install && npm run build`. That completed successfully, then went back to the source directory and ran this command:
`cargo build --target=aarch64-unknown-linux-gnu` but then got an error complaining about not finding the openssl directory, so, as I'm on an arch-based distro, I updated the variable to `OPENSSL_DIR=/etc/ssl`, reran the build command and now getting this error:
```
error: failed to run custom build command for `openssl-sys v0.9.97`

Caused by:
  process didn't exit successfully: `~/git/cookcli/target/debug/build/openssl-sys-1595e419a48e6e95/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = /etc/ssl

  --- stderr
  thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.97/build/main.rs:87:9:
  OpenSSL include directory does not exist: /etc/ssl/include
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
     1: core::panicking::panic_fmt
               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
     2: build_script_main::main
               at ./build/main.rs:87:9
     3: core::ops::function::FnOnce::call_once
               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

I'm officially out of my depth and not sure how to fix this issue..... Any ideas?

**Comment by dubadub** [comment]
> Edit 2: I suspect this might have something to do with needing an aarch64 version of openssl?
Yes, you're absolutely right. Cross-compilation doesn't work on CI either with the same reason. I'm trying to understand how to fix that now.

**Comment by dubadub** [comment]
Hey @shayaknyc  I managed to fixed the issue after specifying to use vendored openssl (I understand it won't try to use system openssl, but compiles it itself). You can also download from releases now https://github.com/cooklang/cookcli/releases/tag/v0.6.0.

**Comment by shayaknyc** [comment]
Ok, so just tried cross-compiling for fun (thanks for the binary in releases), I'm now getting this bizarre error:

```
/usr/bin/ld: /home/user/git/cookcli/target/aarch64-unknown-linux-gnu/release/deps/cook-efe01f08d31fd3f9.cook.a6b721450809a676-cgu.00.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/user/git/cookcli/target/aarch64-unknown-linux-gnu/release/deps/cook-efe01f08d31fd3f9.cook.a6b721450809a676-cgu.00.rcgu.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
          

error: could not compile `cook` (bin "cook") due to previous error
```

Can't figure for the life of me what this means....
