### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by johnmckinzie** [cooklang/cookcli#97]
I'm running cookcli on Pop!_OS 22.04 LTS. When I run it, I get the following error:

`cannot execute binary file: Exec format error`

I'm running 0.7.1.

**Comment by dubadub** [comment]
Hi @johnmckinzie, could you please confirm what architecture do you run: x86_64, arm or aarch64. Also what is the architecture of your system? Thanks!

**Comment by johnmckinzie** [comment]
My bad. I downloaded the wrong arch. Thanks for the quick response.
